import { setIcon } from 'obsidian';

/* 
 *
 * this code was generated by an AI
 * TODO: Write a proper Doc for the following function.
 * Understand the Function, and ens ure it is good for production
 */


/**
 *
 * Svelte Action to apply an Obsidian internal icon to an element.
 * @param node The HTMLElement Svelte provides.
 * @param iconId The Obsidian icon ID (e.g., 'dice', 'settings').
 **/
export function obsidianIcon(node: HTMLElement, iconId: string | null) {
	const icon = (id: string | null) => {
		if (id) {
			setIcon(node, id);
		} else {
			node.empty(); // Null safety: clear icon if ID is missing
		}
	};

	icon(iconId);

	return {
		update: icon, // Allows the icon to change reactively
	};
}
